# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest4():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_test4(self):
    # Get
    self.driver.get("https://sandbox.moodledemo.net/")
    self.driver.implicitly_wait(10)
    self.driver.set_window_size(1520, 816)
    # Login and change language
    self.driver.find_element(By.CSS_SELECTOR, ".langbutton").click()
    # Some time, when i use moodle, it change to another version 
    # self.driver.find_element(By.CSS_SELECTOR, "ul.navbar-nav > li:last-child").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(103)").click()
    self.driver.find_element(By.LINK_TEXT, "Đăng nhập").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-wrapper").click()
    self.driver.find_element(By.ID, "username").send_keys("student")
    self.driver.find_element(By.ID, "password").send_keys("sandbox")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    
    # User Information
    self.driver.find_element(By.CSS_SELECTOR, ".userbutton").click()
    self.driver.find_element(By.LINK_TEXT, "Hồ sơ").click()
    self.driver.find_element(By.LINK_TEXT, "Sửa hồ sơ cá nhân").click()
    self.driver.implicitly_wait(10)
    self.driver.find_element(By.ID, "collapseElement-0").click()
    
    # Click Update
    self.driver.find_element(By.CSS_SELECTOR, ".fa-file-o").click()
    self.driver.find_element(By.LINK_TEXT, "Tải lên một tài liệu").click()
    
    element = self.driver.find_element(By.NAME, "repo_upload_file")
    element.send_keys("C:\\Users\\Admin\\Desktop\\Ftho-Py\\FakeData\\maxminus.png")
    self.driver.implicitly_wait(20)
    self.driver.find_element(By.XPATH, "(//button[contains(text(),'Đăng tải tệp này')])[1]").click()
    self.driver.find_element(By.XPATH, "//input[@id='id_submitbutton']").click()
    
    time.sleep(10)
    assert self.driver.find_element(By.CSS_SELECTOR, ".alert.alert-success span").text == "×"
    self.vars["myVar"] = self.driver.execute_script("const divElement = document.querySelector(\'.alert.alert-success.alert-block.fade.in.alert-dismissible\');const changesSavedText = divElement.textContent.trim(); return changesSavedText;")
    expected = "Đã lưu các thay đổi\n    \n        ×\n        Bỏ qua thông báo này"
    assert self.vars["myVar"] == expected
    
    # time.sleep(10)
  
